helm2to3: add missing bin directory
During an upgrade script it is observed an error:
Error: fork/exec /root/.local/share/helm/plugins/2to3/bin/2to3:
no such file or directory

'helm 2to3' fails because it is expected to be in bin directory ([1]).

We provide this structure in the package itself instead of downloading
from github ([2] + [3])

[1]: https://github.com/helm/helm-2to3/blob/v0.10.0/plugin.yaml#L5
[2]: https://opendev.org/starlingx/config/src/commit/8ccf1c235abd8ec522cbd131f9e9870ab463b71c/controllerconfig/controllerconfig/upgrade-scripts/63-helm-v2-to-v3-rel_migration.sh#L35
[3]: https://github.com/helm/helm-2to3/blob/v0.10.0/scripts/install_plugin.sh#L5

Test:
PASS: Call script 63-helm-v2-to-v3-rel_migration.sh and observe
      no error

Story: 2009138
Task: 45584
JIRA: CGTS-42062
JIRA: CGTS-42815
Signed-off-by: Dan Voiculeasa <dan.voiculeasa@windriver.com>
Change-Id: I7ea76407d57f162f51058bc2ecf143147dafbde8
(cherry picked from commit ff802a37ab9676d29269f437f24e15774e8102cd)